# Generated by Django 5.2.9 on 2025-12-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(verbose_name='پاسخ سوالات')),
                ('total_score', models.PositiveSmallIntegerField(editable=False, verbose_name='جمع امتیاز')),
                ('average_score', models.FloatField(editable=False, verbose_name='میانگین امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
    ]
