# Generated by Django 5.2.9 on 2025-12-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
